definitions:
  models.Experience:
    properties:
      company:
        type: string
      created_at:
        type: string
      description:
        type: string
      end_date:
        type: string
      is_active:
        type: boolean
      link:
        type: string
      role:
        description: Id          string     `json:"id" db:"id"`
        type: string
      start_date:
        type: string
      tech_stack:
        items:
          type: string
        type: array
      updated_at:
        type: string
    type: object
  models.Projects:
    properties:
      category:
        type: string
      created_at:
        type: string
      description:
        type: string
      id:
        type: string
      image_url:
        type: string
      title:
        type: string
      updated_at:
        type: string
      year:
        type: string
    type: object
  response.BaseResponse-array_models_Experience:
    properties:
      code:
        type: integer
      data:
        items:
          $ref: '#/definitions/models.Experience'
        type: array
      message:
        type: string
      status:
        type: boolean
    type: object
  response.BaseResponse-array_models_Projects:
    properties:
      code:
        type: integer
      data:
        items:
          $ref: '#/definitions/models.Projects'
        type: array
      message:
        type: string
      status:
        type: boolean
    type: object
  response.BaseResponse-models_Experience:
    properties:
      code:
        type: integer
      data:
        $ref: '#/definitions/models.Experience'
      message:
        type: string
      status:
        type: boolean
    type: object
  response.BaseResponse-models_Projects:
    properties:
      code:
        type: integer
      data:
        $ref: '#/definitions/models.Projects'
      message:
        type: string
      status:
        type: boolean
    type: object
info:
  contact: {}
paths:
  /experience:
    get:
      consumes:
      - application/json
      description: Take all experience data
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.BaseResponse-array_models_Experience'
      summary: Get All Experience
      tags:
      - Experience
  /experience/{id}:
    get:
      consumes:
      - application/json
      description: Get deail experience data
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.BaseResponse-models_Experience'
      summary: Get Detail Experience
      tags:
      - Experience
  /projects:
    get:
      consumes:
      - application/json
      description: Take all projects data
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.BaseResponse-array_models_Projects'
      summary: Get All Projects
      tags:
      - Projects
  /projects/{id}:
    get:
      consumes:
      - application/json
      description: Get specific project data by ID
      parameters:
      - description: Project ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.BaseResponse-models_Projects'
      summary: Get Project Detail
      tags:
      - Projects
swagger: "2.0"
