name: Go Portfolio BE

on:
  push:
    branches: ["main"] # Pastikan ini sesuai nama branch kamu (main/master)
    # Hapus dulu bagian 'paths' agar setiap push men-trigger CI (untuk testing awal)

  # Tambahan sakti: Mengizinkan trigger manual lewat tombol
  workflow_dispatch:

jobs:
  # Job 1: Quality Check (Lint & Test)
  test:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      # Lint Code (Clean Code check)
      - name: Run Linter (golangci-lint)
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.6

      # Install dependencies
      - name: Install Dependencies
        run: go mod download

      # Run unit test
      # - name: Run Tests
      #   run: go test -v ./...

  # Job 2: Build Check
  build:
    name: Build Check
    runs-on: ubuntu-latest
    needs: test # Run if test success
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Build Binary
        run: go build -v ./...
